# Generated by Django 5.1 on 2024-08-14 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户信息"},
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
