# Generated by Django 5.1 on 2024-08-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        max_length=30, null=True, unique=True, verbose_name="用户名"
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=30, null=True, verbose_name="密码"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=30, null=True, unique=True, verbose_name="邮箱"
                    ),
                ),
            ],
        ),
    ]
