# Generated by Django 5.1 on 2024-08-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="uploader/mlist/"),
        ),
        migrations.AlterField(
            model_name="mlist",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="uploader/mlist/"),
        ),
    ]
