# Generated by Django 5.1 on 2024-08-14 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(max_length=100, null=True, verbose_name="标题"),
                ),
                ("content", models.TextField(null=True, verbose_name="内容")),
                (
                    "publish_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.user"
                    ),
                ),
            ],
        ),
    ]
