# Generated by Django 5.1 on 2024-08-14 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_alter_article_options_alter_article_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="update_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
