# Generated by Django 5.1 on 2024-08-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0004_alter_article_options_alter_article_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
