# Generated by Django 5.1 on 2024-08-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_article_create_at_article_update_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-publish_date"],
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.IntegerField(
                auto_created=True, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
